name: Publish Dev Release
on:
  repository_dispatch:
    types: [x3dom-pushed]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{steps.build_number.outputs.BUILD_NUMBER}}
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Get build number
        id: build_number
        run: echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - name: Build release
        run: |
          npm install
          npm run build
      - name: Remove archive
        run: find dist/ -type f -name '*.zip' -delete
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x3dom-dist
          path: dist/
          retention-days: 1
  update:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      has_changed: ${{ steps.add_commit.outputs.committed }}
    steps:
      - name: Checkout current head
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Check if dist folder exists
        id: check_dist
        uses: andstor/file-existence-action@v2
        with:
          files: "dist"
      - name: Remove entire dist-folder
        if: steps.check_dist.outputs.files_exists == 'true'
        run: git rm -r dist/
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: x3dom-dist
          path: dist/
      - name: Add and Commit
        id: add_commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/'
          message: ${{github.event.client_payload.message}}
  publish:
    runs-on: ubuntu-latest
    needs: [build,update]
    steps:
      - name: Checkout new head
        if: needs.update.outputs.has_changed == 'true'
        uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Publish release
        if: needs.update.outputs.has_changed == 'true'
        uses: "ncipollo/release-action@v1"
        with:
          tag: b${{ needs.build.outputs.build_number }}
          token: "${{ secrets.REPO_ACCESS_TOKEN }}"
          prerelease: false
          artifacts: dist/*.js
      - name: Remove old releases
        if: needs.update.outputs.has_changed == 'true'
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
            
